Create table operations(
    Warehouse_ID VARCHAR(50),
    Location VARCHAR(100),
    Product_Category VARCHAR(100),
    Monthly_Sales FLOAT,
    Current_Stock FLOAT,
    Warehouse_Capacity FLOAT,
    Shipping_Time_Days FLOAT,
    Order_Processing_Time FLOAT,
    Operational_Cost FLOAT,
    Storage_Cost FLOAT,
    Transportation_Cost FLOAT,
    Demand_Forecast FLOAT,
    Stockout_Risk FLOAT,
    Return_Rate FLOAT,
    Damaged_Goods FLOAT,
    Inventory_Turnover FLOAT,
    Delivery_Efficiency FLOAT,
    Total_Cost FLOAT,
    Estimated_Profit FLOAT,
    Stock_Utilization FLOAT,
    Demand_Gap FLOAT,
    Risk_Score FLOAT
);